# Generated by Django 5.0.7 on 2024-08-05 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('site', models.URLField()),
                ('inicio_atividade', models.DateField()),
                ('descricao', models.TextField()),
                ('data_final_captacao', models.DateField()),
                ('percentual_equity', models.PositiveSmallIntegerField()),
                ('estagio', models.CharField(choices=[('I', 'Tenho apenas uma idea'), ('MVP', 'Possuo um MVP'), ('MVPP', 'Possuo um MVP com clientes pagantes'), ('E', 'Empresa pronta para escalar')], default='I', max_length=4)),
                ('area', models.CharField(choices=[('ED', 'Ed-tech'), ('FT', 'Fintech'), ('AT', 'Agrotech')], max_length=3)),
                ('publico_alvo', models.CharField(choices=[('B2B', 'Business to Business (B2B)'), ('B2C', 'Business to Consumer (B2C)')], default='B2B', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pitch', models.FileField(upload_to='pitchs')),
                ('logo', models.FileField(upload_to='logo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
