# Generated by Django 5.0.7 on 2024-08-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0003_metricas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metricas',
            new_name='Metrica',
        ),
    ]
